// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/5/2026, 1:38:37 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/ubuntu/way-trades-restore/way-trades-main--main/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/plugins/**/*.{js,ts,mjs}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/composables/**/*.{js,ts,mjs}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/utils/**/*.{js,ts,mjs}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ubuntu/way-trades-restore/way-trades-main--main/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;